[package]
name = "macos-unifiedlogs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["test_data"]
# this feature is usefull for testing, you can run only tests with 'cargo t --no-default-features'
test_data = []

[dependencies]
nom = "7.1.3"
serde_json = "1.0.117"
serde = { version = "1.0.203", features = ["derive"] }
log = "0.4.21"
lz4_flex = "0.11.3"
byteorder = "1.5.0"
plist = "1.6.1"
regex = "1.10.5"
base64 = "0.22.1"
chrono = "0.4.38"

[dev-dependencies]
simplelog = "0.12.2"
csv = "1.3.0"
chrono = "0.4.38"
criterion = "0.5.1"
anyhow = "1.0"

[[bench]]
name = "high_sierra_benchmark"
harness = false

[[bench]]
name = "big_sur_benchmark"
harness = false

[[bench]]
name = "monterey_benchmark"
harness = false
