[package]
name = "macos-unifiedlogs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7.1.3"
serde_json = "1.0.128"
serde = { version = "1.0.210", features = ["derive"] }
log = "0.4.22"
lz4_flex = "0.11.3"
byteorder = "1.5.0"
plist = "1.7.0"
regex = "1.10.6"
base64 = "0.22.1"
chrono = "0.4.38"

[dev-dependencies]
simplelog = "0.12.2"
csv = "1.3.0"
chrono = "0.4.38"
criterion = "0.5.1"

[[bench]]
name = "high_sierra_benchmark"
harness = false

[[bench]]
name = "big_sur_benchmark"
harness = false

[[bench]]
name = "monterey_benchmark"
harness = false
